version: "2"

services:
  webapp:
    build: ./nginx
#    image: nginx-test
    ports:
    - "80:80"
    volumes:
    - ./dev-app:/app
    networks:
    - code-network
  php:
      image: php:7-fpm
      volumes:
      - ./dev-app:/app
      networks:
          - code-network
networks:
    code-network:
        driver: bridge